# Practical - 9

In [1]:
import pandas as pd 
import numpy as np 

In [ ]:
df=pd.read_csv('/content/spam.csv', encoding='latin-1')
df

In [ ]:
import re 
import nltk 
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer 


In [ ]:
stemming = PorterStemmer() 
corpus = [] 
for i in range (0,len(df)):  
     s1 = re.sub('[^a-zA-Z]',repl = ' ',string = df['v2'][i])    
     s1.lower()     
     s1 = s1.split()     
     s1 = [stemming.stem(word) 
     for word in s1 if word not in set(stopwords.words('english'))]     
     s1 = ' '.join(s1)     
     corpus.append(s1) 

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer 
countvectorizer =CountVectorizer() 

In [ ]:
x = countvectorizer.fit_transform(corpus).toarray() 
print(x) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
y = df['v1'].values 
print(y) 

['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, stratify=y,random_state=2) 

In [ ]:
from sklearn.naive_bayes import MultinomialNB 
multinomialnb = MultinomialNB() 
multinomialnb.fit(x_train,y_train) 

MultinomialNB()

In [ ]:
y_pred = multinomialnb.predict(x_test) 
print(y_pred)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.metrics import accuracy_score 

In [ ]:
print(classification_report(y_test,y_pred)) 
print("accuracy_score: ",accuracy_score(y_test,y_pred)) 

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99      1448
        spam       0.92      0.93      0.92       224

    accuracy                           0.98      1672
   macro avg       0.95      0.96      0.96      1672
weighted avg       0.98      0.98      0.98      1672

accuracy_score:  0.979066985645933
